window.esdocSearchIndex = [
  [
    "browser-mpris2/src/browser/main/carrier.js~carrier",
    "class/src/browser/main/carrier.js~Carrier.html",
    "<span>Carrier</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/carrier.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/main/host.js~host",
    "class/src/browser/main/host.js~Host.html",
    "<span>Host</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/host.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/main/globals.js~loopstatus",
    "variable/index.html#static-variable-LoopStatus",
    "<span>LoopStatus</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/globals.js</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/main/globals.js~messagemethod",
    "variable/index.html#static-variable-MessageMethod",
    "<span>MessageMethod</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/globals.js</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/main/globals.js~messageproperty",
    "variable/index.html#static-variable-MessageProperty",
    "<span>MessageProperty</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/globals.js</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/main/globals.js~messagetype",
    "variable/index.html#static-variable-MessageType",
    "<span>MessageType</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/globals.js</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/providers/netflix.js~netflixpage",
    "class/src/browser/providers/netflix.js~NetflixPage.html",
    "<span>NetflixPage</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/netflix.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/netflix.js~netflixplayback",
    "class/src/browser/providers/netflix.js~NetflixPlayback.html",
    "<span>NetflixPlayback</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/netflix.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/netflix.js~netflixplayer",
    "class/src/browser/providers/netflix.js~NetflixPlayer.html",
    "<span>NetflixPlayer</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/netflix.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/main/page.js~page",
    "class/src/browser/main/page.js~Page.html",
    "<span>Page</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/page.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/main/playback.js~playback",
    "class/src/browser/main/playback.js~Playback.html",
    "<span>Playback</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/playback.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/main/globals.js~playbackstatus",
    "variable/index.html#static-variable-PlaybackStatus",
    "<span>PlaybackStatus</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/globals.js</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/main/player.js~player",
    "class/src/browser/main/player.js~Player.html",
    "<span>Player</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/main/player.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/soundcloud.js~soundcloudplayback",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html",
    "<span>SoundCloudPlayback</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/soundcloud.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/soundcloud.js~soundcloudplayer",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayer.html",
    "<span>SoundCloudPlayer</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/soundcloud.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/spotify.js~spotifyplayback",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html",
    "<span>SpotifyPlayback</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/spotify.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/spotify.js~spotifyplayer",
    "class/src/browser/providers/spotify.js~SpotifyPlayer.html",
    "<span>SpotifyPlayer</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/spotify.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/popup/version.js~version",
    "class/src/browser/popup/version.js~Version.html",
    "<span>Version</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/popup/version.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/youtube-music.js~youtubemusicplayback",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html",
    "<span>YouTubeMusicPlayback</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/youtube-music.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/youtube-music.js~youtubemusicplayer",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayer.html",
    "<span>YouTubeMusicPlayer</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/youtube-music.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/youtube.js~youtubepage",
    "class/src/browser/providers/youtube.js~YouTubePage.html",
    "<span>YouTubePage</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/youtube.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/youtube.js~youtubeplayback",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html",
    "<span>YouTubePlayback</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/youtube.js</span>",
    "class"
  ],
  [
    "browser-mpris2/src/browser/providers/youtube.js~youtubeplayer",
    "class/src/browser/providers/youtube.js~YouTubePlayer.html",
    "<span>YouTubePlayer</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/providers/youtube.js</span>",
    "class"
  ],
  [
    "browser-mpris2~carrier",
    "variable/index.html#static-variable-carrier",
    "<span>carrier</span> <span class=\"search-result-import-path\">browser-mpris2</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/background/proxy.js~connections",
    "variable/index.html#static-variable-connections",
    "<span>connections</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/background/proxy.js</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/background/proxy.js~host",
    "variable/index.html#static-variable-host",
    "<span>host</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/background/proxy.js</span>",
    "variable"
  ],
  [
    "browser-mpris2~host",
    "variable/index.html#static-variable-host",
    "<span>host</span> <span class=\"search-result-import-path\">browser-mpris2</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/popup/popup.js~manifestdata",
    "variable/index.html#static-variable-manifestData",
    "<span>manifestData</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/popup/popup.js</span>",
    "variable"
  ],
  [
    "browser-mpris2~page",
    "variable/index.html#static-variable-page",
    "<span>page</span> <span class=\"search-result-import-path\">browser-mpris2</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/background/proxy.js~pages",
    "variable/index.html#static-variable-pages",
    "<span>pages</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/background/proxy.js</span>",
    "variable"
  ],
  [
    "browser-mpris2~playback",
    "variable/index.html#static-variable-playback",
    "<span>playback</span> <span class=\"search-result-import-path\">browser-mpris2</span>",
    "variable"
  ],
  [
    "browser-mpris2/src/browser/background/proxy.js~raisetab",
    "function/index.html#static-function-raiseTab",
    "<span>raiseTab</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/background/proxy.js</span>",
    "function"
  ],
  [
    "browser-mpris2/src/browser/background/proxy.js~removetab",
    "function/index.html#static-function-removeTab",
    "<span>removeTab</span> <span class=\"search-result-import-path\">browser-mpris2/src/browser/background/proxy.js</span>",
    "function"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber1",
    "Carrier tests",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber28",
    "Carrier tests Carrier.clear",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber29",
    "Carrier tests Carrier.clear ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber45",
    "Carrier tests Carrier.onlyUpdated",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber155",
    "Carrier tests Carrier.payloadFrom",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber156",
    "Carrier tests Carrier.payloadFrom ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber202",
    "Carrier tests Carrier.requestPayload",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber203",
    "Carrier tests Carrier.requestPayload ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber12",
    "Carrier tests Carrier.store",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/carrier.spec.js.html#lineNumber13",
    "Carrier tests Carrier.store ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/host.spec.js.html#lineNumber1",
    "Host tests",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/host.spec.js.html#lineNumber65",
    "Host tests Host.command",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/host.spec.js.html#lineNumber20",
    "Host tests Host.get",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/host.spec.js.html#lineNumber22",
    "Host tests Host.get ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/host.spec.js.html#lineNumber94",
    "Host tests Host.messageListener",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/host.spec.js.html#lineNumber37",
    "Host tests Host.set",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/page.spec.js.html#lineNumber1",
    "Page tests",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/page.spec.js.html#lineNumber23",
    "Page tests Page.registerPlayer",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/page.spec.js.html#lineNumber57",
    "Page tests Page.registerPlayer ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/page.spec.js.html#lineNumber39",
    "Page tests Page.registerPlayer ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/page.spec.js.html#lineNumber24",
    "Page tests Page.registerPlayer ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/page.spec.js.html#lineNumber74",
    "Page tests page.onMutate",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber1",
    "Playback tests",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber67",
    "Playback tests Playback.getLoopStatus",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber12",
    "Playback tests Playback.getStatus",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber18",
    "Playback tests Playback.getStatus ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber30",
    "Playback tests Playback.getStatus ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber89",
    "Playback tests Playback.setActivePlayer",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber91",
    "Playback tests Playback.setActivePlayer ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber103",
    "Playback tests Playback.setActivePlayer ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/playback.spec.js.html#lineNumber43",
    "Playback tests Playback.setLoopStatus",
    "test"
  ],
  [
    "player src/browser/main/player.js~player,player",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber4",
    "Player tests",
    "test"
  ],
  [
    "player#getcover src/browser/main/player.js~player#getcover,player#getcover",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber222",
    "Player tests Feature:",
    "test"
  ],
  [
    "player#getid src/browser/main/player.js~player#getid,player#getid",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber25",
    "Player tests Player.getId",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber26",
    "Player tests Player.getId ",
    "test"
  ],
  [
    "player#getlength src/browser/main/player.js~player#getlength,player#getlength",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber56",
    "Player tests Player.getLength",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber251",
    "Player tests Player.getPosition",
    "test"
  ],
  [
    "player#getrate src/browser/main/player.js~player#getrate,player#getrate",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber148",
    "Player tests Player.getRate",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber468",
    "Player tests Player.getSiteDomain",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber292",
    "Player tests Player.getUrl",
    "test"
  ],
  [
    "player#getvolume src/browser/main/player.js~player#getvolume,player#getvolume",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber77",
    "Player tests Player.getVolume",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber487",
    "Player tests Player.isHidden",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber499",
    "Player tests Player.isHidden ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber488",
    "Player tests Player.isHidden ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber311",
    "Player tests Player.isLooping",
    "test"
  ],
  [
    "player#isplaying src/browser/main/player.js~player#isplaying,player#isplaying",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber36",
    "Player tests Player.isPlaying",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber511",
    "Player tests Player.isValid",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber345",
    "Player tests Player.pause",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber346",
    "Player tests Player.pause ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber360",
    "Player tests Player.pause ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber270",
    "Player tests Player.play",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber271",
    "Player tests Player.play ",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber376",
    "Player tests Player.playPause",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber427",
    "Player tests Player.seek",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber328",
    "Player tests Player.setLoop",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber448",
    "Player tests Player.setPosition",
    "test"
  ],
  [
    "player#setrate src/browser/main/player.js~player#setrate,player#setrate",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber125",
    "Player tests Player.setRate",
    "test"
  ],
  [
    "player#setvolume src/browser/main/player.js~player#setvolume,player#setvolume",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber102",
    "Player tests Player.setVolume",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber404",
    "Player tests Player.stop",
    "test"
  ],
  [
    "player#gettitle src/browser/main/player.js~player#gettitle,player#gettitle",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber172",
    "Player tests Test player's title integration",
    "test"
  ],
  [
    "player#getartists src/browser/main/player.js~player#getartists,player#getartists",
    "test-file/tests/browser/main/player.spec.js.html#lineNumber197",
    "Player tests The artists are parsed correctly from the url",
    "test"
  ],
  [
    "",
    "test-file/tests/browser/popup/version.spec.js.html#lineNumber1",
    "Version tests",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/browser/background/commands.js",
    "file/src/browser/background/commands.js.html",
    "src/browser/background/commands.js",
    "file"
  ],
  [
    "src/browser/background/proxy.js",
    "file/src/browser/background/proxy.js.html",
    "src/browser/background/proxy.js",
    "file"
  ],
  [
    "src/browser/background/updater.js",
    "file/src/browser/background/updater.js.html",
    "src/browser/background/updater.js",
    "file"
  ],
  [
    "src/browser/init.js",
    "file/src/browser/init.js.html",
    "src/browser/init.js",
    "file"
  ],
  [
    "src/browser/main/carrier.js",
    "file/src/browser/main/carrier.js.html",
    "src/browser/main/carrier.js",
    "file"
  ],
  [
    "src/browser/main/carrier.js~carrier#clear",
    "class/src/browser/main/carrier.js~Carrier.html#instance-method-clear",
    "src/browser/main/carrier.js~Carrier#clear",
    "method"
  ],
  [
    "src/browser/main/carrier.js~carrier#constructor",
    "class/src/browser/main/carrier.js~Carrier.html#instance-constructor-constructor",
    "src/browser/main/carrier.js~Carrier#constructor",
    "method"
  ],
  [
    "src/browser/main/carrier.js~carrier#last",
    "class/src/browser/main/carrier.js~Carrier.html#instance-member-last",
    "src/browser/main/carrier.js~Carrier#last",
    "member"
  ],
  [
    "src/browser/main/carrier.js~carrier#onlyupdated",
    "class/src/browser/main/carrier.js~Carrier.html#instance-method-onlyUpdated",
    "src/browser/main/carrier.js~Carrier#onlyUpdated",
    "method"
  ],
  [
    "src/browser/main/carrier.js~carrier#payloadfrom",
    "class/src/browser/main/carrier.js~Carrier.html#instance-method-payloadFrom",
    "src/browser/main/carrier.js~Carrier#payloadFrom",
    "method"
  ],
  [
    "src/browser/main/carrier.js~carrier#requestpayload",
    "class/src/browser/main/carrier.js~Carrier.html#instance-method-requestPayload",
    "src/browser/main/carrier.js~Carrier#requestPayload",
    "method"
  ],
  [
    "src/browser/main/carrier.js~carrier#store",
    "class/src/browser/main/carrier.js~Carrier.html#instance-method-store",
    "src/browser/main/carrier.js~Carrier#store",
    "method"
  ],
  [
    "src/browser/main/globals.js",
    "file/src/browser/main/globals.js.html",
    "src/browser/main/globals.js",
    "file"
  ],
  [
    "src/browser/main/globals.js~metadata",
    "typedef/index.html#static-typedef-Metadata",
    "src/browser/main/globals.js~Metadata",
    "typedef"
  ],
  [
    "src/browser/main/globals.js~payload",
    "typedef/index.html#static-typedef-Payload",
    "src/browser/main/globals.js~Payload",
    "typedef"
  ],
  [
    "src/browser/main/host.js",
    "file/src/browser/main/host.js.html",
    "src/browser/main/host.js",
    "file"
  ],
  [
    "src/browser/main/host.js~host#carrier",
    "class/src/browser/main/host.js~Host.html#instance-member-carrier",
    "src/browser/main/host.js~Host#carrier",
    "member"
  ],
  [
    "src/browser/main/host.js~host#change",
    "class/src/browser/main/host.js~Host.html#instance-method-change",
    "src/browser/main/host.js~Host#change",
    "method"
  ],
  [
    "src/browser/main/host.js~host#command",
    "class/src/browser/main/host.js~Host.html#instance-method-command",
    "src/browser/main/host.js~Host#command",
    "method"
  ],
  [
    "src/browser/main/host.js~host#constructor",
    "class/src/browser/main/host.js~Host.html#instance-constructor-constructor",
    "src/browser/main/host.js~Host#constructor",
    "method"
  ],
  [
    "src/browser/main/host.js~host#get",
    "class/src/browser/main/host.js~Host.html#instance-method-get",
    "src/browser/main/host.js~Host#get",
    "method"
  ],
  [
    "src/browser/main/host.js~host#messagelistener",
    "class/src/browser/main/host.js~Host.html#instance-method-messageListener",
    "src/browser/main/host.js~Host#messageListener",
    "method"
  ],
  [
    "src/browser/main/host.js~host#playback",
    "class/src/browser/main/host.js~Host.html#instance-member-playback",
    "src/browser/main/host.js~Host#playback",
    "member"
  ],
  [
    "src/browser/main/host.js~host#port",
    "class/src/browser/main/host.js~Host.html#instance-member-port",
    "src/browser/main/host.js~Host#port",
    "member"
  ],
  [
    "src/browser/main/host.js~host#quit",
    "class/src/browser/main/host.js~Host.html#instance-method-quit",
    "src/browser/main/host.js~Host#quit",
    "method"
  ],
  [
    "src/browser/main/host.js~host#return",
    "class/src/browser/main/host.js~Host.html#instance-method-return",
    "src/browser/main/host.js~Host#return",
    "method"
  ],
  [
    "src/browser/main/host.js~host#seeked",
    "class/src/browser/main/host.js~Host.html#instance-method-seeked",
    "src/browser/main/host.js~Host#seeked",
    "method"
  ],
  [
    "src/browser/main/host.js~host#sendmessage",
    "class/src/browser/main/host.js~Host.html#instance-method-sendMessage",
    "src/browser/main/host.js~Host#sendMessage",
    "method"
  ],
  [
    "src/browser/main/host.js~host#set",
    "class/src/browser/main/host.js~Host.html#instance-method-set",
    "src/browser/main/host.js~Host#set",
    "method"
  ],
  [
    "src/browser/main/host.js~host#source",
    "class/src/browser/main/host.js~Host.html#instance-member-source",
    "src/browser/main/host.js~Host#source",
    "member"
  ],
  [
    "src/browser/main/host.js~host#start",
    "class/src/browser/main/host.js~Host.html#instance-method-start",
    "src/browser/main/host.js~Host#start",
    "method"
  ],
  [
    "src/browser/main/page.js",
    "file/src/browser/main/page.js.html",
    "src/browser/main/page.js",
    "file"
  ],
  [
    "src/browser/main/page.js~page#_changesobserver",
    "class/src/browser/main/page.js~Page.html#instance-member-_changesObserver",
    "src/browser/main/page.js~Page#_changesObserver",
    "member"
  ],
  [
    "src/browser/main/page.js~page#_mediaobserver",
    "class/src/browser/main/page.js~Page.html#instance-member-_mediaObserver",
    "src/browser/main/page.js~Page#_mediaObserver",
    "member"
  ],
  [
    "src/browser/main/page.js~page#checkformediaelements",
    "class/src/browser/main/page.js~Page.html#instance-method-checkForMediaElements",
    "src/browser/main/page.js~Page#checkForMediaElements",
    "method"
  ],
  [
    "src/browser/main/page.js~page#constructor",
    "class/src/browser/main/page.js~Page.html#instance-constructor-constructor",
    "src/browser/main/page.js~Page#constructor",
    "method"
  ],
  [
    "src/browser/main/page.js~page#document",
    "class/src/browser/main/page.js~Page.html#instance-member-document",
    "src/browser/main/page.js~Page#document",
    "member"
  ],
  [
    "src/browser/main/page.js~page#elements",
    "class/src/browser/main/page.js~Page.html#instance-member-elements",
    "src/browser/main/page.js~Page#elements",
    "member"
  ],
  [
    "src/browser/main/page.js~page#getactiveplayer",
    "class/src/browser/main/page.js~Page.html#instance-method-getActivePlayer",
    "src/browser/main/page.js~Page#getActivePlayer",
    "method"
  ],
  [
    "src/browser/main/page.js~page#geticon",
    "class/src/browser/main/page.js~Page.html#instance-method-getIcon",
    "src/browser/main/page.js~Page#getIcon",
    "method"
  ],
  [
    "src/browser/main/page.js~page#gettitle",
    "class/src/browser/main/page.js~Page.html#instance-method-getTitle",
    "src/browser/main/page.js~Page#getTitle",
    "method"
  ],
  [
    "src/browser/main/page.js~page#host",
    "class/src/browser/main/page.js~Page.html#instance-member-host",
    "src/browser/main/page.js~Page#host",
    "member"
  ],
  [
    "src/browser/main/page.js~page#observeforchanges",
    "class/src/browser/main/page.js~Page.html#instance-method-observeForChanges",
    "src/browser/main/page.js~Page#observeForChanges",
    "method"
  ],
  [
    "src/browser/main/page.js~page#observeformedia",
    "class/src/browser/main/page.js~Page.html#instance-method-observeForMedia",
    "src/browser/main/page.js~Page#observeForMedia",
    "method"
  ],
  [
    "src/browser/main/page.js~page#onmutate",
    "class/src/browser/main/page.js~Page.html#instance-method-onMutate",
    "src/browser/main/page.js~Page#onMutate",
    "method"
  ],
  [
    "src/browser/main/page.js~page#playback",
    "class/src/browser/main/page.js~Page.html#instance-member-playback",
    "src/browser/main/page.js~Page#playback",
    "member"
  ],
  [
    "src/browser/main/page.js~page#players",
    "class/src/browser/main/page.js~Page.html#instance-member-players",
    "src/browser/main/page.js~Page#players",
    "member"
  ],
  [
    "src/browser/main/page.js~page#registerplayer",
    "class/src/browser/main/page.js~Page.html#instance-method-registerPlayer",
    "src/browser/main/page.js~Page#registerPlayer",
    "method"
  ],
  [
    "src/browser/main/page.js~page#setactiveplayer",
    "class/src/browser/main/page.js~Page.html#instance-method-setActivePlayer",
    "src/browser/main/page.js~Page#setActivePlayer",
    "method"
  ],
  [
    "src/browser/main/playback.js",
    "file/src/browser/main/playback.js.html",
    "src/browser/main/playback.js",
    "file"
  ],
  [
    "src/browser/main/playback.js~playback#activeplayer",
    "class/src/browser/main/playback.js~Playback.html#instance-member-activePlayer",
    "src/browser/main/playback.js~Playback#activePlayer",
    "member"
  ],
  [
    "src/browser/main/playback.js~playback#cangonext",
    "class/src/browser/main/playback.js~Playback.html#instance-method-canGoNext",
    "src/browser/main/playback.js~Playback#canGoNext",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#cangoprevious",
    "class/src/browser/main/playback.js~Playback.html#instance-method-canGoPrevious",
    "src/browser/main/playback.js~Playback#canGoPrevious",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#constructor",
    "class/src/browser/main/playback.js~Playback.html#instance-constructor-constructor",
    "src/browser/main/playback.js~Playback#constructor",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#controls",
    "class/src/browser/main/playback.js~Playback.html#instance-member-controls",
    "src/browser/main/playback.js~Playback#controls",
    "member"
  ],
  [
    "src/browser/main/playback.js~playback#getidentity",
    "class/src/browser/main/playback.js~Playback.html#instance-method-getIdentity",
    "src/browser/main/playback.js~Playback#getIdentity",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#getloopstatus",
    "class/src/browser/main/playback.js~Playback.html#instance-method-getLoopStatus",
    "src/browser/main/playback.js~Playback#getLoopStatus",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#getposition",
    "class/src/browser/main/playback.js~Playback.html#instance-method-getPosition",
    "src/browser/main/playback.js~Playback#getPosition",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#getrate",
    "class/src/browser/main/playback.js~Playback.html#instance-method-getRate",
    "src/browser/main/playback.js~Playback#getRate",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#getstatus",
    "class/src/browser/main/playback.js~Playback.html#instance-method-getStatus",
    "src/browser/main/playback.js~Playback#getStatus",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#getvolume",
    "class/src/browser/main/playback.js~Playback.html#instance-method-getVolume",
    "src/browser/main/playback.js~Playback#getVolume",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#isshuffle",
    "class/src/browser/main/playback.js~Playback.html#instance-method-isShuffle",
    "src/browser/main/playback.js~Playback#isShuffle",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#next",
    "class/src/browser/main/playback.js~Playback.html#instance-method-next",
    "src/browser/main/playback.js~Playback#next",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#pause",
    "class/src/browser/main/playback.js~Playback.html#instance-method-pause",
    "src/browser/main/playback.js~Playback#pause",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#play",
    "class/src/browser/main/playback.js~Playback.html#instance-method-play",
    "src/browser/main/playback.js~Playback#play",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#previous",
    "class/src/browser/main/playback.js~Playback.html#instance-method-previous",
    "src/browser/main/playback.js~Playback#previous",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#seek",
    "class/src/browser/main/playback.js~Playback.html#instance-method-seek",
    "src/browser/main/playback.js~Playback#seek",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#setactiveplayer",
    "class/src/browser/main/playback.js~Playback.html#instance-method-setActivePlayer",
    "src/browser/main/playback.js~Playback#setActivePlayer",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#setloopstatus",
    "class/src/browser/main/playback.js~Playback.html#instance-method-setLoopStatus",
    "src/browser/main/playback.js~Playback#setLoopStatus",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#setposition",
    "class/src/browser/main/playback.js~Playback.html#instance-method-setPosition",
    "src/browser/main/playback.js~Playback#setPosition",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#setrate",
    "class/src/browser/main/playback.js~Playback.html#instance-method-setRate",
    "src/browser/main/playback.js~Playback#setRate",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#setshuffle",
    "class/src/browser/main/playback.js~Playback.html#instance-method-setShuffle",
    "src/browser/main/playback.js~Playback#setShuffle",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#setvolume",
    "class/src/browser/main/playback.js~Playback.html#instance-method-setVolume",
    "src/browser/main/playback.js~Playback#setVolume",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#stop",
    "class/src/browser/main/playback.js~Playback.html#instance-method-stop",
    "src/browser/main/playback.js~Playback#stop",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#togglefullscreen",
    "class/src/browser/main/playback.js~Playback.html#instance-method-toggleFullScreen",
    "src/browser/main/playback.js~Playback#toggleFullScreen",
    "method"
  ],
  [
    "src/browser/main/playback.js~playback#toggleplayback",
    "class/src/browser/main/playback.js~Playback.html#instance-method-togglePlayback",
    "src/browser/main/playback.js~Playback#togglePlayback",
    "method"
  ],
  [
    "src/browser/main/player.js",
    "file/src/browser/main/player.js.html",
    "src/browser/main/player.js",
    "file"
  ],
  [
    "src/browser/main/player.js~player#url",
    "class/src/browser/main/player.js~Player.html#instance-member-URL",
    "src/browser/main/player.js~Player#URL",
    "member"
  ],
  [
    "src/browser/main/player.js~player#constructor",
    "class/src/browser/main/player.js~Player.html#instance-constructor-constructor",
    "src/browser/main/player.js~Player#constructor",
    "method"
  ],
  [
    "src/browser/main/player.js~player#element",
    "class/src/browser/main/player.js~Player.html#instance-member-element",
    "src/browser/main/player.js~Player#element",
    "member"
  ],
  [
    "src/browser/main/player.js~player#getartists",
    "class/src/browser/main/player.js~Player.html#instance-method-getArtists",
    "src/browser/main/player.js~Player#getArtists",
    "method"
  ],
  [
    "src/browser/main/player.js~player#getcover",
    "class/src/browser/main/player.js~Player.html#instance-method-getCover",
    "src/browser/main/player.js~Player#getCover",
    "method"
  ],
  [
    "src/browser/main/player.js~player#getid",
    "class/src/browser/main/player.js~Player.html#instance-method-getId",
    "src/browser/main/player.js~Player#getId",
    "method"
  ],
  [
    "src/browser/main/player.js~player#getlength",
    "class/src/browser/main/player.js~Player.html#instance-method-getLength",
    "src/browser/main/player.js~Player#getLength",
    "method"
  ],
  [
    "src/browser/main/player.js~player#getposition",
    "class/src/browser/main/player.js~Player.html#instance-method-getPosition",
    "src/browser/main/player.js~Player#getPosition",
    "method"
  ],
  [
    "src/browser/main/player.js~player#getrate",
    "class/src/browser/main/player.js~Player.html#instance-method-getRate",
    "src/browser/main/player.js~Player#getRate",
    "method"
  ],
  [
    "src/browser/main/player.js~player#getsitedomain",
    "class/src/browser/main/player.js~Player.html#instance-method-getSiteDomain",
    "src/browser/main/player.js~Player#getSiteDomain",
    "method"
  ],
  [
    "src/browser/main/player.js~player#gettitle",
    "class/src/browser/main/player.js~Player.html#instance-method-getTitle",
    "src/browser/main/player.js~Player#getTitle",
    "method"
  ],
  [
    "src/browser/main/player.js~player#geturl",
    "class/src/browser/main/player.js~Player.html#instance-method-getUrl",
    "src/browser/main/player.js~Player#getUrl",
    "method"
  ],
  [
    "src/browser/main/player.js~player#getvolume",
    "class/src/browser/main/player.js~Player.html#instance-method-getVolume",
    "src/browser/main/player.js~Player#getVolume",
    "method"
  ],
  [
    "src/browser/main/player.js~player#host",
    "class/src/browser/main/player.js~Player.html#instance-member-host",
    "src/browser/main/player.js~Player#host",
    "member"
  ],
  [
    "src/browser/main/player.js~player#initdefaultmedialisteners",
    "class/src/browser/main/player.js~Player.html#instance-method-initDefaultMediaListeners",
    "src/browser/main/player.js~Player#initDefaultMediaListeners",
    "method"
  ],
  [
    "src/browser/main/player.js~player#ishidden",
    "class/src/browser/main/player.js~Player.html#instance-method-isHidden",
    "src/browser/main/player.js~Player#isHidden",
    "method"
  ],
  [
    "src/browser/main/player.js~player#islooping",
    "class/src/browser/main/player.js~Player.html#instance-method-isLooping",
    "src/browser/main/player.js~Player#isLooping",
    "method"
  ],
  [
    "src/browser/main/player.js~player#ismuted",
    "class/src/browser/main/player.js~Player.html#instance-method-isMuted",
    "src/browser/main/player.js~Player#isMuted",
    "method"
  ],
  [
    "src/browser/main/player.js~player#ispaused",
    "class/src/browser/main/player.js~Player.html#instance-method-isPaused",
    "src/browser/main/player.js~Player#isPaused",
    "method"
  ],
  [
    "src/browser/main/player.js~player#isplaying",
    "class/src/browser/main/player.js~Player.html#instance-method-isPlaying",
    "src/browser/main/player.js~Player#isPlaying",
    "method"
  ],
  [
    "src/browser/main/player.js~player#isstopped",
    "class/src/browser/main/player.js~Player.html#instance-method-isStopped",
    "src/browser/main/player.js~Player#isStopped",
    "method"
  ],
  [
    "src/browser/main/player.js~player#isvalid",
    "class/src/browser/main/player.js~Player.html#instance-method-isValid",
    "src/browser/main/player.js~Player#isValid",
    "method"
  ],
  [
    "src/browser/main/player.js~player#page",
    "class/src/browser/main/player.js~Player.html#instance-member-page",
    "src/browser/main/player.js~Player#page",
    "member"
  ],
  [
    "src/browser/main/player.js~player#pause",
    "class/src/browser/main/player.js~Player.html#instance-method-pause",
    "src/browser/main/player.js~Player#pause",
    "method"
  ],
  [
    "src/browser/main/player.js~player#play",
    "class/src/browser/main/player.js~Player.html#instance-method-play",
    "src/browser/main/player.js~Player#play",
    "method"
  ],
  [
    "src/browser/main/player.js~player#playpause",
    "class/src/browser/main/player.js~Player.html#instance-method-playPause",
    "src/browser/main/player.js~Player#playPause",
    "method"
  ],
  [
    "src/browser/main/player.js~player#refresh",
    "class/src/browser/main/player.js~Player.html#instance-method-refresh",
    "src/browser/main/player.js~Player#refresh",
    "method"
  ],
  [
    "src/browser/main/player.js~player#seek",
    "class/src/browser/main/player.js~Player.html#instance-method-seek",
    "src/browser/main/player.js~Player#seek",
    "method"
  ],
  [
    "src/browser/main/player.js~player#setloop",
    "class/src/browser/main/player.js~Player.html#instance-method-setLoop",
    "src/browser/main/player.js~Player#setLoop",
    "method"
  ],
  [
    "src/browser/main/player.js~player#setposition",
    "class/src/browser/main/player.js~Player.html#instance-method-setPosition",
    "src/browser/main/player.js~Player#setPosition",
    "method"
  ],
  [
    "src/browser/main/player.js~player#setrate",
    "class/src/browser/main/player.js~Player.html#instance-method-setRate",
    "src/browser/main/player.js~Player#setRate",
    "method"
  ],
  [
    "src/browser/main/player.js~player#setvolume",
    "class/src/browser/main/player.js~Player.html#instance-method-setVolume",
    "src/browser/main/player.js~Player#setVolume",
    "method"
  ],
  [
    "src/browser/main/player.js~player#stop",
    "class/src/browser/main/player.js~Player.html#instance-method-stop",
    "src/browser/main/player.js~Player#stop",
    "method"
  ],
  [
    "src/browser/main/player.js~player#togglefullscreen",
    "class/src/browser/main/player.js~Player.html#instance-method-toggleFullScreen",
    "src/browser/main/player.js~Player#toggleFullScreen",
    "method"
  ],
  [
    "src/browser/popup/popup.js",
    "file/src/browser/popup/popup.js.html",
    "src/browser/popup/popup.js",
    "file"
  ],
  [
    "src/browser/popup/version.js",
    "file/src/browser/popup/version.js.html",
    "src/browser/popup/version.js",
    "file"
  ],
  [
    "src/browser/popup/version.js~version#constructor",
    "class/src/browser/popup/version.js~Version.html#instance-constructor-constructor",
    "src/browser/popup/version.js~Version#constructor",
    "method"
  ],
  [
    "src/browser/popup/version.js~version#isgreaterthan",
    "class/src/browser/popup/version.js~Version.html#instance-method-isGreaterThan",
    "src/browser/popup/version.js~Version#isGreaterThan",
    "method"
  ],
  [
    "src/browser/providers/netflix.js",
    "file/src/browser/providers/netflix.js.html",
    "src/browser/providers/netflix.js",
    "file"
  ],
  [
    "src/browser/providers/netflix.js~netflixpage#registerplayer",
    "class/src/browser/providers/netflix.js~NetflixPage.html#instance-method-registerPlayer",
    "src/browser/providers/netflix.js~NetflixPage#registerPlayer",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayback#cangonext",
    "class/src/browser/providers/netflix.js~NetflixPlayback.html#instance-method-canGoNext",
    "src/browser/providers/netflix.js~NetflixPlayback#canGoNext",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayback#next",
    "class/src/browser/providers/netflix.js~NetflixPlayback.html#instance-method-next",
    "src/browser/providers/netflix.js~NetflixPlayback#next",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayback#seek",
    "class/src/browser/providers/netflix.js~NetflixPlayback.html#instance-method-seek",
    "src/browser/providers/netflix.js~NetflixPlayback#seek",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayback#setloopstatus",
    "class/src/browser/providers/netflix.js~NetflixPlayback.html#instance-method-setLoopStatus",
    "src/browser/providers/netflix.js~NetflixPlayback#setLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayback#setposition",
    "class/src/browser/providers/netflix.js~NetflixPlayback.html#instance-method-setPosition",
    "src/browser/providers/netflix.js~NetflixPlayback#setPosition",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayback#setrate",
    "class/src/browser/providers/netflix.js~NetflixPlayback.html#instance-method-setRate",
    "src/browser/providers/netflix.js~NetflixPlayback#setRate",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayer#getartists",
    "class/src/browser/providers/netflix.js~NetflixPlayer.html#instance-method-getArtists",
    "src/browser/providers/netflix.js~NetflixPlayer#getArtists",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayer#getid",
    "class/src/browser/providers/netflix.js~NetflixPlayer.html#instance-method-getId",
    "src/browser/providers/netflix.js~NetflixPlayer#getId",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayer#gettitle",
    "class/src/browser/providers/netflix.js~NetflixPlayer.html#instance-method-getTitle",
    "src/browser/providers/netflix.js~NetflixPlayer#getTitle",
    "method"
  ],
  [
    "src/browser/providers/netflix.js~netflixplayer#isvalid",
    "class/src/browser/providers/netflix.js~NetflixPlayer.html#instance-method-isValid",
    "src/browser/providers/netflix.js~NetflixPlayer#isValid",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js",
    "file/src/browser/providers/soundcloud.js.html",
    "src/browser/providers/soundcloud.js",
    "file"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#cangonext",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-canGoNext",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#canGoNext",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#cangoprevious",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-canGoPrevious",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#canGoPrevious",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#getloopstatus",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-getLoopStatus",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#getLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#isshuffle",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-isShuffle",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#isShuffle",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#next",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-next",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#next",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#previous",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-previous",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#previous",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#setloopstatus",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-setLoopStatus",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#setLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#setrate",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-setRate",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#setRate",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#setshuffle",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-setShuffle",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#setShuffle",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayback#setvolume",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayback.html#instance-method-setVolume",
    "src/browser/providers/soundcloud.js~SoundCloudPlayback#setVolume",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayer#getartists",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayer.html#instance-method-getArtists",
    "src/browser/providers/soundcloud.js~SoundCloudPlayer#getArtists",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayer#getcover",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayer.html#instance-method-getCover",
    "src/browser/providers/soundcloud.js~SoundCloudPlayer#getCover",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayer#getid",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayer.html#instance-method-getId",
    "src/browser/providers/soundcloud.js~SoundCloudPlayer#getId",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayer#getlength",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayer.html#instance-method-getLength",
    "src/browser/providers/soundcloud.js~SoundCloudPlayer#getLength",
    "method"
  ],
  [
    "src/browser/providers/soundcloud.js~soundcloudplayer#gettitle",
    "class/src/browser/providers/soundcloud.js~SoundCloudPlayer.html#instance-method-getTitle",
    "src/browser/providers/soundcloud.js~SoundCloudPlayer#getTitle",
    "method"
  ],
  [
    "src/browser/providers/spotify.js",
    "file/src/browser/providers/spotify.js.html",
    "src/browser/providers/spotify.js",
    "file"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#cangonext",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-canGoNext",
    "src/browser/providers/spotify.js~SpotifyPlayback#canGoNext",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#cangoprevious",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-canGoPrevious",
    "src/browser/providers/spotify.js~SpotifyPlayback#canGoPrevious",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#getloopstatus",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-getLoopStatus",
    "src/browser/providers/spotify.js~SpotifyPlayback#getLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#isshuffle",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-isShuffle",
    "src/browser/providers/spotify.js~SpotifyPlayback#isShuffle",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#next",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-next",
    "src/browser/providers/spotify.js~SpotifyPlayback#next",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#previous",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-previous",
    "src/browser/providers/spotify.js~SpotifyPlayback#previous",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#setloopstatus",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-setLoopStatus",
    "src/browser/providers/spotify.js~SpotifyPlayback#setLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#setshuffle",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-setShuffle",
    "src/browser/providers/spotify.js~SpotifyPlayback#setShuffle",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayback#setvolume",
    "class/src/browser/providers/spotify.js~SpotifyPlayback.html#instance-method-setVolume",
    "src/browser/providers/spotify.js~SpotifyPlayback#setVolume",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayer#getartists",
    "class/src/browser/providers/spotify.js~SpotifyPlayer.html#instance-method-getArtists",
    "src/browser/providers/spotify.js~SpotifyPlayer#getArtists",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayer#getcover",
    "class/src/browser/providers/spotify.js~SpotifyPlayer.html#instance-method-getCover",
    "src/browser/providers/spotify.js~SpotifyPlayer#getCover",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayer#gettitle",
    "class/src/browser/providers/spotify.js~SpotifyPlayer.html#instance-method-getTitle",
    "src/browser/providers/spotify.js~SpotifyPlayer#getTitle",
    "method"
  ],
  [
    "src/browser/providers/spotify.js~spotifyplayer#isplaying",
    "class/src/browser/providers/spotify.js~SpotifyPlayer.html#instance-method-isPlaying",
    "src/browser/providers/spotify.js~SpotifyPlayer#isPlaying",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js",
    "file/src/browser/providers/youtube-music.js.html",
    "src/browser/providers/youtube-music.js",
    "file"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#cangonext",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-canGoNext",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#canGoNext",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#cangoprevious",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-canGoPrevious",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#canGoPrevious",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#getloopstatus",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-getLoopStatus",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#getLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#isactionpressed",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-isActionPressed",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#isActionPressed",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#next",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-next",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#next",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#previous",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-previous",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#previous",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#setloopstatus",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-setLoopStatus",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#setLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#setrate",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-setRate",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#setRate",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#setshuffle",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-setShuffle",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#setShuffle",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayback#setvolume",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayback.html#instance-method-setVolume",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayback#setVolume",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayer#getartists",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayer.html#instance-method-getArtists",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayer#getArtists",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayer#getcover",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayer.html#instance-method-getCover",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayer#getCover",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayer#getid",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayer.html#instance-method-getId",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayer#getId",
    "method"
  ],
  [
    "src/browser/providers/youtube-music.js~youtubemusicplayer#gettitle",
    "class/src/browser/providers/youtube-music.js~YouTubeMusicPlayer.html#instance-method-getTitle",
    "src/browser/providers/youtube-music.js~YouTubeMusicPlayer#getTitle",
    "method"
  ],
  [
    "src/browser/providers/youtube.js",
    "file/src/browser/providers/youtube.js.html",
    "src/browser/providers/youtube.js",
    "file"
  ],
  [
    "src/browser/providers/youtube.js~youtubepage#registerplayer",
    "class/src/browser/providers/youtube.js~YouTubePage.html#instance-method-registerPlayer",
    "src/browser/providers/youtube.js~YouTubePage#registerPlayer",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#cangonext",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-canGoNext",
    "src/browser/providers/youtube.js~YouTubePlayback#canGoNext",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#cangoprevious",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-canGoPrevious",
    "src/browser/providers/youtube.js~YouTubePlayback#canGoPrevious",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#getloopstatus",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-getLoopStatus",
    "src/browser/providers/youtube.js~YouTubePlayback#getLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#isactionpressed",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-isActionPressed",
    "src/browser/providers/youtube.js~YouTubePlayback#isActionPressed",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#isbuttondisabled",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-isButtonDisabled",
    "src/browser/providers/youtube.js~YouTubePlayback#isButtonDisabled",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#iscontrolavailable",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-isControlAvailable",
    "src/browser/providers/youtube.js~YouTubePlayback#isControlAvailable",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#isshuffle",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-isShuffle",
    "src/browser/providers/youtube.js~YouTubePlayback#isShuffle",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#next",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-next",
    "src/browser/providers/youtube.js~YouTubePlayback#next",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#previous",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-previous",
    "src/browser/providers/youtube.js~YouTubePlayback#previous",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#setloopstatus",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-setLoopStatus",
    "src/browser/providers/youtube.js~YouTubePlayback#setLoopStatus",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#setrate",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-setRate",
    "src/browser/providers/youtube.js~YouTubePlayback#setRate",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#setshuffle",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-setShuffle",
    "src/browser/providers/youtube.js~YouTubePlayback#setShuffle",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayback#setvolume",
    "class/src/browser/providers/youtube.js~YouTubePlayback.html#instance-method-setVolume",
    "src/browser/providers/youtube.js~YouTubePlayback#setVolume",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayer#getartists",
    "class/src/browser/providers/youtube.js~YouTubePlayer.html#instance-method-getArtists",
    "src/browser/providers/youtube.js~YouTubePlayer#getArtists",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayer#getcover",
    "class/src/browser/providers/youtube.js~YouTubePlayer.html#instance-method-getCover",
    "src/browser/providers/youtube.js~YouTubePlayer#getCover",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayer#getid",
    "class/src/browser/providers/youtube.js~YouTubePlayer.html#instance-method-getId",
    "src/browser/providers/youtube.js~YouTubePlayer#getId",
    "method"
  ],
  [
    "src/browser/providers/youtube.js~youtubeplayer#gettitle",
    "class/src/browser/providers/youtube.js~YouTubePlayer.html#instance-method-getTitle",
    "src/browser/providers/youtube.js~YouTubePlayer#getTitle",
    "method"
  ],
  [
    "tests/browser/main/carrier.spec.js",
    "test-file/tests/browser/main/carrier.spec.js.html",
    "tests/browser/main/carrier.spec.js",
    "testFile"
  ],
  [
    "tests/browser/main/host.spec.js",
    "test-file/tests/browser/main/host.spec.js.html",
    "tests/browser/main/host.spec.js",
    "testFile"
  ],
  [
    "tests/browser/main/page.spec.js",
    "test-file/tests/browser/main/page.spec.js.html",
    "tests/browser/main/page.spec.js",
    "testFile"
  ],
  [
    "tests/browser/main/playback.spec.js",
    "test-file/tests/browser/main/playback.spec.js.html",
    "tests/browser/main/playback.spec.js",
    "testFile"
  ],
  [
    "tests/browser/main/player.spec.js",
    "test-file/tests/browser/main/player.spec.js.html",
    "tests/browser/main/player.spec.js",
    "testFile"
  ],
  [
    "tests/browser/popup/version.spec.js",
    "test-file/tests/browser/popup/version.spec.js.html",
    "tests/browser/popup/version.spec.js",
    "testFile"
  ]
]